class_name MapDefinitions
extends RefCounted

const TILE_SIZE = 32
const MAP_WIDTH = 50
const MAP_HEIGHT = 50

# 50×50のマップ密度を従来の50×30に近づける。
const ROOM_MAX_COUNT = 30
const ROOM_MIN_SIZE = 3
const ROOM_MAX_SIZE = 8

enum CellType { WALL, FLOOR, WATER, STAIRS, GRASS, STAIRS_BLUE, STAIRS_GREEN, DOOR_CLOSED, DOOR_OPEN, DOOR_LOCKED, ICE, LAVA, ASH, CRYSTAL_FLOOR, STAIRS_RED, STAIRS_PURPLE, PIT, STAIRS_UP, STAIRS_GOLD, TREE, TREE_FRUIT, ROCK }

enum WorldCell { SEA, GRASS, FOREST, MOUNTAIN, VILLAGE, DUNGEON, ROAD }
